package.json

- update clean script to be cross platform and work with new build process
- auto run clean script before build script

update clean script

---

tsconfig.build.json

that path doesn't exists in this project

build: remove "typings" import from tsconfig

---

.nycrc.json
package.json

generate lcov for codecov
https://app.codecov.io/gh/vitaly-t/iter-ops/

update nyc config

---

src/types.ts

Simple fix of the `Operation` type. (#114 is more about improving the definition)

fix: operation definition

---

.github/renovate.json

Setup [Renovate](https://github.com/marketplace/renovate) to automatically manage dependencies.
You'll need to install the [Renovate](https://github.com/marketplace/renovate) app for this to work.

Setup renovate

---

src/types/common.ts

fix typings

---

src/ops/on-end.ts
test/ops/on-end/async.ts
test/ops/on-end/sync.ts

On end improvement

---

src/helpers.ts
src/typeguards.ts
src/types/common.ts
src/types/index.ts
src/utils.ts
test/utils.spec.ts

fix: handling of SharedArrayBuffer

---

src/ops/reduce.ts
src/typeguards.ts
test/ops/reduce/async.ts
test/ops/reduce/types/async.test-d.ts
test/ops/reduce/types/sync.test-d.ts

feat: add async callback support to operator `reduce`

---

src/index.ts
src/ops/skip-while.ts
test/ops/skip-while/async.ts
test/ops/skip-while/index.spec.ts
test/ops/skip-while/sync.ts
test/ops/skip-while/types/async.test-d.ts
test/ops/skip-while/types/sync.test-d.ts

* Adds new operator `skipWhile`
* Marks operator `start` as `deprecated`

adding operator skipWhile - #193

---

src/index.ts
src/ops/take-while.ts
test/ops/take-while/async.ts
test/ops/take-while/index.spec.ts
test/ops/take-while/sync.ts
test/ops/take-while/types/async.test-d.ts
test/ops/take-while/types/sync.test-d.ts

* Adds operator `takeWhile`
* Marks operator `stop` as `deprecated`.

adding operator takeWhile - #193

---

README.md
src/index.ts
src/ops/skip-while.ts
src/ops/take-until.ts
src/ops/take-while.ts
test/ops/take-until/async.ts
test/ops/take-until/index.spec.ts
test/ops/take-until/sync.ts
test/ops/take-until/types/async.test-d.ts
test/ops/take-until/types/sync.test-d.ts

Take until

---

README.md
src/index.ts
src/ops/skip-until.ts
test/ops/skip-until/async.ts
test/ops/skip-until/index.spec.ts
test/ops/skip-until/sync.ts
test/ops/skip-until/types/async.test-d.ts
test/ops/skip-until/types/sync.test-d.ts

adding operator skipUntil - #193

---

src/typeguards.ts
test/typeguards/index.spec.ts
test/typeguards/isIteratorResult.ts

fix: detection of keys within objects

---

test/helpers.spec.ts

This test will fix the coverage issue.

test: add missing test case for toIterable

---

package.json
src/ops/flat.ts
test/ops/flat/sync.ts
typedoc.json

Add "skip" support to operatof "flat"

---

src/index.ts
src/ops/retry.ts
test/ops/retry/index.spec.ts
test/ops/retry/sync.ts

Sync retry

---

src/ops/async/delay.ts
src/ops/timeout.ts
test/ops/timeout/async.ts

As per #237, refactoring the timeout, tests + some documentation.

refactoring timeout + tests

---

test/ops/delay/async.ts

adding test for delay

---

package.json

build: fix npm scripts on windows
